/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizadorcompi1;
import java.io.BufferedReader;
import javax.swing.JOptionPane;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.File;
import java.io.FileReader;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jeany
 */
public class Inicio extends javax.swing.JFrame {
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaEntrada = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        bttAutomatas = new javax.swing.JButton();
        bttAnalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAbrir = new javax.swing.JMenu();
        MenuGuardar = new javax.swing.JMenu();
        MenuGuardarComo = new javax.swing.JMenu();
        MenuSalida = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaEntrada.setColumns(20);
        AreaEntrada.setRows(5);
        jScrollPane1.setViewportView(AreaEntrada);

        jLabel1.setText("Archivo de entrada");

        bttAutomatas.setText("Generar automatas");
        bttAutomatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAutomatasActionPerformed(evt);
            }
        });

        bttAnalizar.setText("Analizar entradas");
        bttAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAnalizarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("Salida");

        MenuAbrir.setText("Abrir");
        MenuAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuAbrirMousePressed(evt);
            }
        });
        jMenuBar1.add(MenuAbrir);

        MenuGuardar.setText("Guardar ");
        MenuGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuGuardarMousePressed(evt);
            }
        });
        jMenuBar1.add(MenuGuardar);

        MenuGuardarComo.setText("Guardar Como");
        jMenuBar1.add(MenuGuardarComo);

        MenuSalida.setText("Salida");
        jMenuBar1.add(MenuSalida);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(bttAutomatas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttAnalizar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttAutomatas)
                    .addComponent(bttAnalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttAutomatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAutomatasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttAutomatasActionPerformed

    private void bttAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAnalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttAnalizarActionPerformed

    private void MenuAbrirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAbrirMousePressed
        //JOptionPane.showMessageDialog(null, "Abrir el archivo");
        String ruta = null;
        JFileChooser seleccionar = new JFileChooser();
        File archivo; 
        FileInputStream entrada; 
        FileOutputStream salida; 
        
        seleccionar.setFileFilter(new FileNameExtensionFilter("Expresiones regulares", "er"));
        int opcion = seleccionar.showOpenDialog(null);
        if(opcion == JFileChooser.APPROVE_OPTION)
        {
            ruta = seleccionar.getSelectedFile().getAbsolutePath();
        }
        String texto = "";
        
        String documento = new String(), path = ruta;
        archivo = new File(path);
        FileReader leer = null;
        BufferedReader docEntrada  = null;
        try {
            leer = new FileReader(archivo);
            docEntrada = new BufferedReader(leer);
            while((texto = docEntrada.readLine()) != null)
            {
                documento += texto + "\n";
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            try {
                if(null != leer)
                {
                    leer.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
        AreaEntrada.setText(documento);
    }//GEN-LAST:event_MenuAbrirMousePressed

    private void MenuGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuGuardarMousePressed
        try {
            String nombre = "";
            JFileChooser MiArchivo = new JFileChooser(System.getProperty("user.dir"));
            MiArchivo.showSaveDialog(this);
            File guardar = MiArchivo.getSelectedFile();
            if(guardar != null)
            {
                nombre = MiArchivo.getSelectedFile().getName();
                FileWriter Guardado = new FileWriter(guardar+".er");
                Guardado.write(AreaEntrada.getText());
                Guardado.close();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_MenuGuardarMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaEntrada;
    private javax.swing.JMenu MenuAbrir;
    private javax.swing.JMenu MenuGuardar;
    private javax.swing.JMenu MenuGuardarComo;
    private javax.swing.JMenu MenuSalida;
    private javax.swing.JButton bttAnalizar;
    private javax.swing.JButton bttAutomatas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
